apiVersion: move2kube.konveyor.io/v1alpha1
kind: ClusterMetadata
metadata:
  name: |
    default/c114-e-us-south-containers:32230/IAM#username
spec:
  storageClasses:
    - default
  apiKindVersionMap:
    APIServer:
      - config.openshift.io/v1
    APIService:
      - apiregistration.k8s.io/v1
      - apiregistration.k8s.io/v1beta1
    Alertmanager:
      - monitoring.coreos.com/v1
    AppliedClusterResourceQuota:
      - quota.openshift.io/v1
    Authentication:
      - config.openshift.io/v1
      - operator.openshift.io/v1
    BGPConfiguration:
      - crd.projectcalico.org/v1
    BGPPeer:
      - crd.projectcalico.org/v1
    BareMetalHost:
      - metal3.io/v1alpha1
    BinaryBuildRequestOptions:
      - build.openshift.io/v1
    Binding:
      - v1
    BlockAffinity:
      - crd.projectcalico.org/v1
    BrokerTemplateInstance:
      - template.openshift.io/v1
    Build:
      - build.openshift.io/v1
      - config.openshift.io/v1
    BuildConfig:
      - build.openshift.io/v1
    BuildLog:
      - build.openshift.io/v1
    BuildRequest:
      - build.openshift.io/v1
    CSIDriver:
      - storage.k8s.io/v1
      - storage.k8s.io/v1beta1
    CSINode:
      - storage.k8s.io/v1
      - storage.k8s.io/v1beta1
    CSISnapshotController:
      - operator.openshift.io/v1
    CatalogSource:
      - operators.coreos.com/v1alpha1
    CertificateSigningRequest:
      - certificates.k8s.io/v1beta1
    ClusterInformation:
      - crd.projectcalico.org/v1
    ClusterOperator:
      - config.openshift.io/v1
    ClusterResourceQuota:
      - quota.openshift.io/v1
    ClusterRole:
      - authorization.openshift.io/v1
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1beta1
    ClusterRoleBinding:
      - authorization.openshift.io/v1
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1beta1
    ClusterServiceVersion:
      - operators.coreos.com/v1alpha1
    ClusterVersion:
      - config.openshift.io/v1
    ComponentStatus:
      - v1
    Config:
      - operator.openshift.io/v1
      - imageregistry.operator.openshift.io/v1
      - samples.operator.openshift.io/v1
    ConfigMap:
      - v1
    Console:
      - config.openshift.io/v1
      - operator.openshift.io/v1
    ConsoleCLIDownload:
      - console.openshift.io/v1
    ConsoleExternalLogLink:
      - console.openshift.io/v1
    ConsoleLink:
      - console.openshift.io/v1
    ConsoleNotification:
      - console.openshift.io/v1
    ConsoleYAMLSample:
      - console.openshift.io/v1
    ContainerRuntimeConfig:
      - machineconfiguration.openshift.io/v1
    ControllerRevision:
      - apps/v1
    CredentialsRequest:
      - cloudcredential.openshift.io/v1
    CronJob:
      - batch/v1beta1
    CustomResourceDefinition:
      - apiextensions.k8s.io/v1
      - apiextensions.k8s.io/v1beta1
    DNS:
      - config.openshift.io/v1
      - operator.openshift.io/v1
    DNSRecord:
      - ingress.operator.openshift.io/v1
    DaemonSet:
      - apps/v1
    Deployment:
      - apps/v1
    DeploymentConfig:
      - apps.openshift.io/v1
    DeploymentConfigRollback:
      - apps.openshift.io/v1
    DeploymentLog:
      - apps.openshift.io/v1
    DeploymentRequest:
      - apps.openshift.io/v1
    EndpointSlice:
      - discovery.k8s.io/v1beta1
    Endpoints:
      - v1
    Etcd:
      - operator.openshift.io/v1
    Event:
      - events.k8s.io/v1beta1
      - v1
    Eviction:
      - v1
    FeatureGate:
      - config.openshift.io/v1
    FelixConfiguration:
      - crd.projectcalico.org/v1
    GlobalNetworkPolicy:
      - crd.projectcalico.org/v1
    GlobalNetworkSet:
      - crd.projectcalico.org/v1
    Group:
      - user.openshift.io/v1
    HorizontalPodAutoscaler:
      - autoscaling/v1
      - autoscaling/v2beta1
      - autoscaling/v2beta2
    HostEndpoint:
      - crd.projectcalico.org/v1
    IPAMBlock:
      - crd.projectcalico.org/v1
    IPAMConfig:
      - crd.projectcalico.org/v1
    IPAMHandle:
      - crd.projectcalico.org/v1
    IPPool:
      - crd.projectcalico.org/v1
      - whereabouts.cni.cncf.io/v1alpha1
    Identity:
      - user.openshift.io/v1
    Image:
      - image.openshift.io/v1
      - config.openshift.io/v1
    ImageContentSourcePolicy:
      - operator.openshift.io/v1alpha1
    ImagePruner:
      - imageregistry.operator.openshift.io/v1
    ImageSignature:
      - image.openshift.io/v1
    ImageStream:
      - image.openshift.io/v1
    ImageStreamImage:
      - image.openshift.io/v1
    ImageStreamImport:
      - image.openshift.io/v1
    ImageStreamLayers:
      - image.openshift.io/v1
    ImageStreamMapping:
      - image.openshift.io/v1
    ImageStreamTag:
      - image.openshift.io/v1
    ImageTag:
      - image.openshift.io/v1
    Infrastructure:
      - config.openshift.io/v1
    Ingress:
      - config.openshift.io/v1
      - networking.k8s.io/v1beta1
      - extensions/v1beta1
    IngressClass:
      - networking.k8s.io/v1beta1
    IngressController:
      - operator.openshift.io/v1
    InstallPlan:
      - operators.coreos.com/v1alpha1
    Installation:
      - operator.tigera.io/v1
    Job:
      - batch/v1
    KubeAPIServer:
      - operator.openshift.io/v1
    KubeControllerManager:
      - operator.openshift.io/v1
    KubeScheduler:
      - operator.openshift.io/v1
    KubeStorageVersionMigrator:
      - operator.openshift.io/v1
    KubeletConfig:
      - machineconfiguration.openshift.io/v1
    Lease:
      - coordination.k8s.io/v1
      - coordination.k8s.io/v1beta1
    LimitRange:
      - v1
    LocalResourceAccessReview:
      - authorization.openshift.io/v1
    LocalSubjectAccessReview:
      - authorization.openshift.io/v1
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1beta1
    MachineConfig:
      - machineconfiguration.openshift.io/v1
    MachineConfigPool:
      - machineconfiguration.openshift.io/v1
    MutatingWebhookConfiguration:
      - admissionregistration.k8s.io/v1
      - admissionregistration.k8s.io/v1beta1
    Namespace:
      - v1
    Network:
      - config.openshift.io/v1
      - operator.openshift.io/v1
    NetworkAttachmentDefinition:
      - k8s.cni.cncf.io/v1
    NetworkPolicy:
      - networking.k8s.io/v1
      - crd.projectcalico.org/v1
    NetworkSet:
      - crd.projectcalico.org/v1
    Node:
      - v1
    NodeMetrics:
      - metrics.k8s.io/v1beta1
    NodeProxyOptions:
      - v1
    OAuth:
      - config.openshift.io/v1
    OAuthAccessToken:
      - oauth.openshift.io/v1
    OAuthAuthorizeToken:
      - oauth.openshift.io/v1
    OAuthClient:
      - oauth.openshift.io/v1
    OAuthClientAuthorization:
      - oauth.openshift.io/v1
    OpenShiftAPIServer:
      - operator.openshift.io/v1
    OpenShiftControllerManager:
      - operator.openshift.io/v1
    OperatorGroup:
      - operators.coreos.com/v1
      - operators.coreos.com/v1alpha2
    OperatorHub:
      - config.openshift.io/v1
    OperatorPKI:
      - network.operator.openshift.io/v1
    OperatorSource:
      - operators.coreos.com/v1
    PackageManifest:
      - packages.operators.coreos.com/v1
    PersistentVolume:
      - v1
    PersistentVolumeClaim:
      - v1
    Pod:
      - v1
    PodAttachOptions:
      - v1
    PodDisruptionBudget:
      - policy/v1beta1
    PodExecOptions:
      - v1
    PodMetrics:
      - metrics.k8s.io/v1beta1
    PodMonitor:
      - monitoring.coreos.com/v1
    PodPortForwardOptions:
      - v1
    PodProxyOptions:
      - v1
    PodSecurityPolicy:
      - policy/v1beta1
    PodSecurityPolicyReview:
      - security.openshift.io/v1
    PodSecurityPolicySelfSubjectReview:
      - security.openshift.io/v1
    PodSecurityPolicySubjectReview:
      - security.openshift.io/v1
    PodTemplate:
      - v1
    PriorityClass:
      - scheduling.k8s.io/v1
      - scheduling.k8s.io/v1beta1
    Profile:
      - tuned.openshift.io/v1
    Project:
      - project.openshift.io/v1
      - config.openshift.io/v1
    ProjectRequest:
      - project.openshift.io/v1
    Prometheus:
      - monitoring.coreos.com/v1
    PrometheusRule:
      - monitoring.coreos.com/v1
    Provisioning:
      - metal3.io/v1alpha1
    Proxy:
      - config.openshift.io/v1
    RBACSync:
      - ibm.com/v1alpha1
    RangeAllocation:
      - security.openshift.io/v1
    ReplicaSet:
      - apps/v1
    ReplicationController:
      - v1
    ResourceAccessReview:
      - authorization.openshift.io/v1
    ResourceQuota:
      - v1
    Role:
      - authorization.openshift.io/v1
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1beta1
    RoleBinding:
      - authorization.openshift.io/v1
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1beta1
    RoleBindingRestriction:
      - authorization.openshift.io/v1
    Route:
      - route.openshift.io/v1
    RuntimeClass:
      - node.k8s.io/v1beta1
    Scale:
      - apps.openshift.io/v1
      - operator.openshift.io/v1
      - apps/v1
      - v1
    Scheduler:
      - config.openshift.io/v1
    Secret:
      - v1
    SecretList:
      - image.openshift.io/v1
    SecurityContextConstraints:
      - security.openshift.io/v1
    SelfSubjectAccessReview:
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1beta1
    SelfSubjectRulesReview:
      - authorization.openshift.io/v1
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1beta1
    Service:
      - v1
    ServiceAccount:
      - v1
    ServiceCA:
      - operator.openshift.io/v1
    ServiceMonitor:
      - monitoring.coreos.com/v1
    ServiceProxyOptions:
      - v1
    StatefulSet:
      - apps/v1
    StorageClass:
      - storage.k8s.io/v1
      - storage.k8s.io/v1beta1
    StorageState:
      - migration.k8s.io/v1alpha1
    StorageVersionMigration:
      - migration.k8s.io/v1alpha1
    SubjectAccessReview:
      - authorization.openshift.io/v1
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1beta1
    SubjectRulesReview:
      - authorization.openshift.io/v1
    Subscription:
      - operators.coreos.com/v1alpha1
    Template:
      - template.openshift.io/v1
    TemplateInstance:
      - template.openshift.io/v1
    ThanosRuler:
      - monitoring.coreos.com/v1
    TigeraStatus:
      - operator.tigera.io/v1
    TokenReview:
      - authentication.k8s.io/v1
      - authentication.k8s.io/v1beta1
    Tuned:
      - tuned.openshift.io/v1
    User:
      - user.openshift.io/v1
    UserIdentityMapping:
      - user.openshift.io/v1
    ValidatingWebhookConfiguration:
      - admissionregistration.k8s.io/v1
      - admissionregistration.k8s.io/v1beta1
    VolumeAttachment:
      - storage.k8s.io/v1
      - storage.k8s.io/v1beta1
